name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  testOnUbuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Install Dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt update
          sudo apt install clang
          sudo apt install "libstdc++6" libx11-xcb-dev libxcb-util-dev libxcb-cursor-dev libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev libfontconfig1-dev libcairo2-dev libgtkmm-3.0-dev libsqlite3-dev libxcb-keysyms1-dev
      - name: Build
        run: ./gradlew linkReleaseStaticLinuxX64 --info
      - name: Generate test report
        run: ./gradlew allTests || true
      - name: Upload Test Report
        uses: actions/upload-artifact@v2.2.1
        with:
          name: reports-linuxX64
          path: interop/build/reports
      - name: Test
        run: ./gradlew allTests

  testOnMacOS:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Build
        run: ./gradlew linkReleaseStaticMacosX64 --info
      - name: Generate test report
        run: ./gradlew allTests || true
      - name: Upload Test Report
        uses: actions/upload-artifact@v2.2.1
        with:
          name: reports-macosX64
          path: interop/build/reports
      - name: Test
        run: ./gradlew allTests

  testOnWindows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Build library
        run: .\gradlew linkReleaseStaticWindowsX64 --info
      - name: Generate test report
        run: .\gradlew allTests || true
      - name: Upload Test Report
        uses: actions/upload-artifact@v2.2.1
        with:
          name: reports-windowsX64
          path: interop/build/reports
      - name: Test
        run: .\gradlew allTests